### ISSUE TITLE
AttributeError: cameraHandler instance has no attribute 'dragTask'

### ISSUE THREAD

**Issue by titov-andrei** [titov-andrei/megarpg#5]
Ошибка при запуске main.py

`/usr/bin/python2.7 /home/andrew/CODE/Python/megarpg/main.py
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "/home/andrew/CODE/Python/megarpg/main.py", line 8, in <module>
    loc = gameLocation()
  File "/home/andrew/CODE/Python/megarpg/modules/location.py", line 16, in __init__
    camera = cameraHandler()
  File "/home/andrew/CODE/Python/megarpg/modules/control.py", line 23, in __init__
    taskMgr.add(self.dragTask, 'dragTask')
AttributeError: cameraHandler instance has no attribute 'dragTask'

Process finished with exit code 1`

**Comment by titov-andrei** [comment]
Поправил отступы в функции def dragTask()
