### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by titov-andrei** [titov-andrei/megarpg#7]
/usr/bin/python2.7 /home/andrew/CODE/Python/megarpg/main.py
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "/home/andrew/CODE/Python/megarpg/main.py", line 4, in <module>
    from modules.location import gameLocation
  File "/home/andrew/CODE/Python/megarpg/modules/location.py", line 7, in <module>
    from modules.control import cameraHandler
  File "/home/andrew/CODE/Python/megarpg/modules/control.py", line 86
    self.pickerQ.sortEntries()
       ^
IndentationError: expected an indented block

Process finished with exit code 1

**Comment by titov-andrei** [comment]
Проблема была с отступами. Поправил.
